apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web-app
  labels:
    app: django-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-web-app
  template:
    metadata:
      labels:
        app: django-web-app
    spec:
      containers:
      - name: django-web-app
        image: sushantjadhavhcl/eshop_django_app:I I20240422
        ports:
        - containerPort: 8000
