apiVersion: v1
kind: Service
metadata:
  name: django-web-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: django-web-app
