apiVersion: v1
kind: Service
metadata:
  name: django-web-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 85
    targetPort: 80
    protocol: TCP
  selector:
    app: django-web-app
