name: Docker Agent

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image and Updateting the deployment files
      run: |
           git config user.email "sushantjadhav416@gmail.com"
           git config user.name "sushantjadhav416"
           TAG_DATE=I
           TAG_DATE+=$(date +'%Y%m%d');
           UP_TAG=$(date +'%Y%m%d')
           docker build -t sushantjadhavhcl/docker_agent:${TAG_DATE} .
           docker push sushantjadhavhcl/docker_agent:${TAG_DATE}
           
